### ISSUE TITLE
Interpolating coordinate at infinity

### ISSUE THREAD

**Issue by sigvaldm** [langmuirproject/langmuir#13]
I have a slight issue concerning interpolating from a set of 4-dimensional points where some are at kappa=inf. The algorithms cannot interpolate from a point at infinity. I see two ways around this:

1. Replace kappa=inf by kappa=1000 in the table of values. This works when trying to interpolate the current for a point with kappa between 0 and 1000, but since extrapolation is not permitted, it fails for kappa>1000 which actually happens if you try to use it for a Maxwellian or Cairns-distributed species having kappa=inf. Thus it becomes necessary not only to alter the mesh coordinates of the points of the tabulated values, but also to cap every point which is to be interpolated to not have kappa above 1000. This is of course a solution, since it only has to be done in one function, but it's not very elegant.

2. Replace kappa by 1/kappa in the table (not other places in the code). This removes all of the above problem, but it raises another question. The interpolated function will in this case not be a piecewise linear function of kappa but a piecewise linear function of 1/kappa. But perhaps this makes just as much sense and is even a better approximation since kappa varies more close to zero? Any thoughts or opinions?

**Comment by diakodarian** [comment]
The kappa-values that have been fitted to experimental measurements are usually in the range [3,6]. So I don't think that could cause any problems for any practical purposes. However, the second option seems more preferable, as it does not restrict the range of valid kappa-values. As long as kappa>3/2, the user should be able to obtain an interpolated value for the collected current. And you're right, the differences in currents are larger between kappa=4 and kappa=6 than between kappa=6 and kappa=100 or kappa=1000.

**Comment by sigvaldm** [comment]
I decided to test both methods and make a plot of current vs. kappa for a spherical probe of 1.5mm and eta=-20 in a n=1e11 and T=1000 electron plasma. That's just slightly above the minimum radius of 0.2 Debye lengths for tables. The kappa dependence is clearly more hyperbolic-like (1/kappa) than linear (kappa) in nature, and it shows:

![interpolation](https://user-images.githubusercontent.com/21025915/48839593-43976600-ed8c-11e8-8bd3-3373a2f4dbf9.png)

I think this settles the case.

**Comment by sigvaldm** [comment]
Only testing missing

**Comment by sigvaldm** [comment]
Done
