### ISSUE TITLE
Wrong value from thermal_current()?

### ISSUE THREAD

**Issue by sigvaldm** [langmuirproject/langmuir#17]
Shouldn't the thermal current, when normalized, be 1 for Maxwellian? It is for the Sphere but not for the Cylinder.

**Comment by sigvaldm** [comment]
I wrote a small test for this function so running pytest should uncover what I believe must be a wrong value.

**Comment by diakodarian** [comment]
The issue is that we are using a different thermal current for the cylindrical probe than the one used by Laframboise. I'll stick with the definition given by Laframboise. This means that we have to regenerate the tables for the cylindrical probe. I'll fix it.

**Comment by diakodarian** [comment]
Fixed the bug. Since thermal_current() wasn't used to normalize the simulation results there's no need to regenerate the tables for the cylindrical probe. It was normalization_current(geometry, species) that's been used for the normalization.

**Comment by sigvaldm** [comment]
Great! And now the following two lines gives the same results, which I think makes sense:

```
OML_current(g, s, 0)
thermal_current(g, s)
```

This appeared to also fix the other test which I had for the tabulated values with thermal currents inserted. If it's okay with you we can close this.

By the way, out of curiosity, what is the other definition of thermal current?

**Comment by diakodarian** [comment]
The other definition (which only appears for the attracted species for Kappa and Kappa-Cairns VDFs) is `I_0 = 2*sqrt(2)*R_p*L_p*q_s*n_s*v_th`. For the Kappa and Kappa-Cairns VDFs this definition seems more natural than `I_0 = sqrt(2*pi)*R_p*L_p*q_s*n_s*v_th`. But I think it is best to stick with the definition given by Laframboise (and others, for the Maxwellian VDF), simply to avoid introducing something new that might cause unnecessary confusion.

**Comment by sigvaldm** [comment]
Right. I see. What confused me was that I expected the same as `OML_current(g, s, 0)` for small radii objects.
