### ISSUE TITLE
Error in get_table()

### ISSUE THREAD

**Issue by diakodarian** [langmuirproject/langmuir#18]
`langmuir/interpolated.py", line 75, in finite_radius_current
    table = get_table(table, flip_kappa=flip_kappa)
TypeError: get_table() got an unexpected keyword argument 'flip_kappa'`

**Comment by sigvaldm** [comment]
Burde ikkje ta så lang tid.

**Comment by sigvaldm** [comment]
Etterkvart vil eg også legge til testar til denne fila, så då skulle slike feil ikkje kunne oppstå.

**Comment by diakodarian** [comment]
Supert! Det printes ut en del ting her og der når jeg kaller på finite_radius_current(). Vi burde kanskje fjerne de også?

**Comment by sigvaldm** [comment]
Ja eg ser på det samtidig. (Burde ikkje du sove no?) :)

**Comment by sigvaldm** [comment]
Funkar det for deg no?

**Comment by diakodarian** [comment]
Ja, det funker nå. Det ser ut som den testen jeg har lagt til for å unngå `RuntimeWarning: divide by zero encountered in true_divide` ikke fungerer lenger. Jeg skal prøve å fikse det.

**Comment by diakodarian** [comment]
Jeg prøver å gjøre ferdig paperet før i morgen, og sende det til W. Sliter litt med å legge det fra meg :-)

**Comment by sigvaldm** [comment]
Ja, den får eg opp her også. Som du kanskje merka har eg tatt bort `species.dist` variabelen. Fant ut at den egentlig var overflødig ettersom kappa og alpha allereie spesifiserar dette entydig. Kanskje eg har introdusert noko då?!

**Comment by sigvaldm** [comment]
Det er alltids meir som kan pussast på, men paperet har tross alt vore i ganske god stand heilt sidan tabellane kom på plass. Du får sette deg eit klokkeslett å prøve å runde av til då, så får du sende det du har til Wojciech då.

**Comment by diakodarian** [comment]
Ja, jeg skal runde av ganske snart. Også får jeg vente på tilbakemeldinger fra Wojciech før jeg finpusser det mer.
