### ISSUE TITLE
Support vectorized voltage inputs

### ISSUE THREAD

**Issue by sigvaldm** [langmuirproject/langmuir#2]

**Comment by sigvaldm** [comment]
I recommend to construct something like this for avoiding if-sentences:

```
I_attr = ...
I_rep = ...
attr = q*V>0
I = I_attr * attr + I_rep * (1-attr)
```

This keeps the entire evaluation vectorized (no slow loops).

**Comment by diakodarian** [comment]
Decided to use numpy's 'where' function. Still avoids if-sentences and no loops are needed.

**Comment by sigvaldm** [comment]
Even better!
