### ISSUE TITLE
Unit test OML_current

### ISSUE THREAD

**Issue by sigvaldm** [langmuirproject/langmuir#4]
E.g. pick some reasonable parameters, compute a current by hand for those parameters, and assert that OML_current also produces those values (to within some precision) in test_langmuir.py.

pytest (with pytest-cov installed) shows which lines are not covered. We aim for covering all lines. Make sure to test both attracted and repelled species currents if using my suggested approach instead of if-sentence. Testing just one means that there can still be an error in the other, despite coverage being 100%.

**Comment by diakodarian** [comment]
I have now tested both attracted and repelled species for Kappa, Cairns and Kappa-Cairns VDFs for spherical and cylindrical geometries. I have also tested the limit `alpha --> 0` for all the cases. The second limit, which is `kappa --> infinity`, is implemented separately, but it is also tested. Basically, all the expressions in `OML_current()` are tested. Tests for thermal currents are also added. Let me know what you think.

There is a function in test_analytical.py, which does not seems to be complete: `test_OML_current_not_normalized_by_default()`

**Comment by sigvaldm** [comment]
I think it looks good. One slight asymmetry I noticed is that you test every combination of attracted/repelled, cylinder/sphere, kappa-cairns/kappa/cairns/maxwellian, except for repelled maxwellian. Since it's a special case of the Cairns distribution for which the repelled current _is_ tested, I don't really expect that a bug will pass through this test undiscovered, but I wonder if perhaps you intended it to be symmetric or if there is a particular reason you chose not to?

**Comment by diakodarian** [comment]
Thanks for pointing this out! Yesterday, when I was implementing the tests, I thought the repelled Maxwellian cases were taken care of by the function `test_OML_current_maxwellian()`. 
But now I see that this function only tests the cylindrical case for attracted species.

I'll add two more testes (for the Maxwellian VDF for repelled species) to `test_OML_current_cairns()`.

**Comment by diakodarian** [comment]
The tests for the repelled Maxwellian species for both spherical and cylindrical geometries are now implemented.

**Comment by sigvaldm** [comment]
>  I thought the repelled Maxwellian cases were taken care of by the function `test_OML_current_maxwellian()`

I had forgotten that. But it's uncomplete, since it only tests attracted species. I think the ones you added are better. I think this can be closed, then.
