### ISSUE TITLE
Thermal currents for Kappa-Cairns?

### ISSUE THREAD

**Issue by sigvaldm** [langmuirproject/langmuir#9]
The function `lafr_norm_current()` which computes the current due to random thermal flux is deprecated since it didn't use the species and geometry objects. The function `normalization_current()` replaces this. This is now also used to compute the constants `I0` inside `OML_current()`. However, this got me thinking. `I0` as it is stands today is actually the thermal current for a Maxwellian velocity distribution, not Kappa-Cairns. It would perhaps make sense to work with the thermal velocity of the given distribution as a normalization current. However, all our results are based on the current definition of `I0` and it would be unfeasible to change it now. However, we could also make a function `thermal_current()` which returns the `thermal_current()` for any distribution.

**Comment by diakodarian** [comment]
Done.
